### PR TITLE
fix machineId Infinity bug, reset global time after one second

### PR DESCRIPTION
**Pull request by iMuFeng**

### CODE REVIEW

**Comment by kaelzhang** [comment]
You can not do this. 

`2 ** o2` which is equivalent to `Math.pow(2, o2)`, is an [exponentiation operator](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Arithmetic_Operators#Exponentiation_(**)) which supported in node >= 7.5

We use `2 ** o2` instead of the left shift `<<` operator due to the weird behavior of integers in JavaScript.

**Comment by iMuFeng** [comment]
Maybe you can test with the script below:

```javascript
let machineIdBitLength = 6
let workerIdBitLength = 4
let serialIdBitLength = 12
let machineId = 1

let o1, o2, o3

    o1 = 2 ** machineIdBitLength * (
      o2 = 2 ** workerIdBitLength * (
        o3 = 2 ** serialIdBitLength
      )
    )

let _machineId = o1 !== o2 && machineId
      ? machineId * 2 ** o2
      : 0    

console.log('o1 = %d, o2 = %d, o3 = %d', o1, o2, o3)
console.log('_machineId = %d', _machineId)
```

**Comment by kaelzhang** [comment]
You are right, it is my fault. the `o2` has already been exponentiated.

**Comment by kaelzhang** [comment]
landed `1.1.5`

**Pull request merged**
